In [1]:
#Q1
import numpy as np
array = np.arange(22,50,2)
print(array)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [5]:
#Q2
import numpy as np
array = np.arange(1,19,2).reshape(3,3)
print(array)
print("Using iteration")
for i in array:
    for j in i:
        print(j)
    print()

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
1
3
5

7
9
11

13
15
17



In [21]:
#Q3
import numpy as np
array = np.array([[2,4,6],
                 [8,10,12],
                 [14,16,18]])
multiply = array*4
print(multiply)
#Creating the identity matrix
identity=np.identity(3)
print("Identity Matrix is")
print(identity)
result = np.dot(multiply,identity)
print("Result Matrix")
print(result)

[[ 8 16 24]
 [32 40 48]
 [56 64 72]]
Identity Matrix is
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Result Matrix
[[ 8. 16. 24.]
 [32. 40. 48.]
 [56. 64. 72.]]


In [25]:
#Q4
import numpy as np
data=[('Charles',155,10),
      ('Xavier',165,12),
      ('Magnito',185,10),
      ('NoOne',155,12)]
dtypes=[('name','U15'),('height',int),('class',int)]
students = np.array(data,dtypes)
sort=np.sort(students, order=['class','height'])
print(sort)

[('Charles', 155, 10) ('Magnito', 185, 10) ('NoOne', 155, 12)
 ('Xavier', 165, 12)]


In [45]:
#Q5
random = [2,5,9,10]
matrix = np.random.choice(random,size=(4,4))
print(matrix)
identity=np.identity(4)
print("Identity matrix")
print(identity)
result = np.dot(matrix,identity)
print("Resultant Matrix is")
print(result)
odd= np.arange(1,32,2).reshape(4,4)
print('Odd Array')
print(odd)
final = result+odd
print("Final reult is")
print(final)

[[ 5 10  2  9]
 [ 9  2 10  2]
 [ 9 10  2  9]
 [ 5 10  9  2]]
Identity matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Resultant Matrix is
[[ 5. 10.  2.  9.]
 [ 9.  2. 10.  2.]
 [ 9. 10.  2.  9.]
 [ 5. 10.  9.  2.]]
Odd Array
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]
Final reult is
[[ 6. 13.  7. 16.]
 [18. 13. 23. 17.]
 [26. 29. 23. 32.]
 [30. 37. 38. 33.]]
